spring.application.name=back_healthy_food_app
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5434/fit-food-oop
spring.datasource.username=postgres
spring.datasource.password=Raza5557
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

app.jwt.secret = XK6lF7rtorwqq0BFXEspu71q+ptfhedXmg3jBGvVwHmYqdisCXfY+Em1aI/114Ir2GvCWCnbtvO4+q5hEjdZ1g==
app.jwt.lifetime = 900000
